extends Object
class_name Overseer
## The Overseer manages/records all flags/events throughout a game

enum EVENT_TYPE {
	TIME, PLAYER_STATUS, 
	PLAYER_DECK, PLAYER_HAND, 
	PLAYER_BATTLEFIELD, PLAYER_MANIFESTATIONS,
	CARD, MANIFESTATION, ENCANTATION,
	FIEND, CHARM, SPELL, CANTRIP
}
enum TURN_FLAGS {
	PLAYER_START, PLAYER_TURN, PLAYER_END, 
	OPPONENT_START, OPPONENT_TURN, OPPONENT_END
}
enum STATUS_FLAGS {
	PLAYER_GAINED, PLAYER_LOST, PLAYER_TARGETED, PLAYER_CHARMED,
	OPPONENT_GAINED, OPPONENT_LOST, OPPONENT_TARGETED, OPPONENT_CHARMED
}
enum DECK_FLAGS {
	SHUFFLED, SEARCHED, CHECKED
}
enum HAND_FLAGS {
	DRAWN
}

var event_enum_table : Array = [
	TURN_FLAGS, STATUS_FLAGS, DECK_FLAGS, HAND_FLAGS
]
